/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FileRegistry {
  export type FileMetaStruct = {
    owner: AddressLike;
    name: string;
    magnetURI: string;
    contentHash: BytesLike;
    registeredAt: BigNumberish;
  };

  export type FileMetaStructOutput = [
    owner: string,
    name: string,
    magnetURI: string,
    contentHash: string,
    registeredAt: bigint
  ] & {
    owner: string;
    name: string;
    magnetURI: string;
    contentHash: string;
    registeredAt: bigint;
  };
}

export interface FileRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "computeFileId"
      | "getByParams"
      | "getFile"
      | "registerFile"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FileRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "computeFileId",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getByParams",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(functionFragment: "getFile", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registerFile",
    values: [string, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "computeFileId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getByParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerFile",
    data: BytesLike
  ): Result;
}

export namespace FileRegisteredEvent {
  export type InputTuple = [
    fileId: BytesLike,
    owner: AddressLike,
    name: string,
    magnetURI: string,
    contentHash: BytesLike
  ];
  export type OutputTuple = [
    fileId: string,
    owner: string,
    name: string,
    magnetURI: string,
    contentHash: string
  ];
  export interface OutputObject {
    fileId: string;
    owner: string;
    name: string;
    magnetURI: string;
    contentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FileRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FileRegistry;
  waitForDeployment(): Promise<this>;

  interface: FileRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  computeFileId: TypedContractMethod<
    [owner: AddressLike, name: string, magnetURI: string],
    [string],
    "view"
  >;

  getByParams: TypedContractMethod<
    [owner: AddressLike, name: string, magnetURI: string],
    [FileRegistry.FileMetaStructOutput],
    "view"
  >;

  getFile: TypedContractMethod<
    [fileId: BytesLike],
    [FileRegistry.FileMetaStructOutput],
    "view"
  >;

  registerFile: TypedContractMethod<
    [name: string, magnetURI: string, contentHash: BytesLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "computeFileId"
  ): TypedContractMethod<
    [owner: AddressLike, name: string, magnetURI: string],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getByParams"
  ): TypedContractMethod<
    [owner: AddressLike, name: string, magnetURI: string],
    [FileRegistry.FileMetaStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFile"
  ): TypedContractMethod<
    [fileId: BytesLike],
    [FileRegistry.FileMetaStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerFile"
  ): TypedContractMethod<
    [name: string, magnetURI: string, contentHash: BytesLike],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "FileRegistered"
  ): TypedContractEvent<
    FileRegisteredEvent.InputTuple,
    FileRegisteredEvent.OutputTuple,
    FileRegisteredEvent.OutputObject
  >;

  filters: {
    "FileRegistered(bytes32,address,string,string,bytes32)": TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;
    FileRegistered: TypedContractEvent<
      FileRegisteredEvent.InputTuple,
      FileRegisteredEvent.OutputTuple,
      FileRegisteredEvent.OutputObject
    >;
  };
}
